import PermContactCalendarOutlinedIcon from "@mui/icons-material/PermContactCalendarOutlined";

const AtomIconPermContactCalendarOutlined = PermContactCalendarOutlinedIcon;
export default AtomIconPermContactCalendarOutlined;
